version: "3"

services:
  wppconnect:
    container_name: wpp-server
    restart: unless-stopped
    build:
      context: .
    volumes:
      - ./config.ts:/usr/src/wpp-server/config.ts
      - ./wppconnect_tokens:/usr/src/wpp-server/tokens
    ports:
      - "21465:21465"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - WPPCONNECT_HOST=${WPPCONNECT_HOST}
    env_file:
      - .env

volumes:
  wppconnect_tokens: {}      