export default {
  secretKey: process.env.SECRET_KEY,
  host: process.env.HOST,
  port: process.env.PORT,
  deviceName: process.env.DEVICE_NAME,
  poweredBy: process.env.POWERED_BY,
  startAllSession: true,
  tokenStoreType: 'file',
  maxListeners: 15,
  customUserDataDir: './userDataDir/',
  webhook: {
    url: null,
    autoDownload: true,
    uploadS3: false,
    readMessage: false,
    allUnreadOnStart: false,
    listenAcks: true,
    onPresenceChanged: true,
    onParticipantsChanged: true,
    onReactionMessage: true,
    onPollResponse: true,
    onRevokedMessage: false,
  },
  archive: {
    enable: false,
    waitTime: 10,
    daysToArchive: 45,
  },
  mapper: {
    enable: false,
    prefix: 'default-',
  },
  log: {
    level: 'error',
    logger: ['console', 'file'],
  },
  createOptions: {
    browserArgs: [
      '--no-sandbox',
      '--disable-setuid-sandbox',
      '--disable-dev-shm-usage',
      '--disable-gpu',
      '--disable-web-security',
      '--disable-features=VizDisplayCompositor',
    ],
    headless: true,
    devtools: false,
    useChrome: true,
    debug: false,
    logQR: true,
    waitForLogin: true,
    protocolTimeout: 180000,
    puppeteerOptions: {
      timeout: 180000,
      protocolTimeout: 180000,
    },
  },
};
